classDiagram


    class Миссия {
        +идентификатор
        +дата
        +место
        +результат
        +стоимость_ущерба
        +комментарий
    }

    class Проклятие {
        +название
        +уровень_угрозы
    }

    class Маг {
        +имя
        +ранг
    }

    class Техника {
        +название
        +тип
        +владелец
        +урон
    }

    class Парсер {
        +определить_формат()
        +извлечь_данные()
    }

    class ФабрикаПарсеров {
        +выбрать_парсер()
    }

    class ИнтерфейсПользователя {
        +выбрать_файл()
        +отобразить_результат()
    }

%% Отношения между классами
    Миссия "1" *-- "1" Проклятие : содержит
    Миссия "1" *-- "0..*" Маг : содержит
    Миссия "1" *-- "0..*" Техника : содержит

    Парсер <|-- XMLПарсер : наследует
    Парсер <|-- JSONПарсер : наследует
    Парсер <|-- TXTПарсер : наследует

    ФабрикаПарсеров --> Парсер : создает
    ИнтерфейсПользователя --> ФабрикаПарсеров : использует
    ИнтерфейсПользователя --> Миссия : отображает